"""empty message

Revision ID: 09db4afac225
Revises: 562eae7d587e
Create Date: 2016-09-17 12:03:54.748185

"""

# revision identifiers, used by Alembic.
revision = '09db4afac225'
down_revision = '562eae7d587e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'product_ibfk_1', 'product', type_='foreignkey')
    op.drop_column('product', 'amount_currency_id')
    op.drop_constraint(u'transaction_ibfk_4', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'status_date')
    op.drop_column('transaction', 'status_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('status_date', sa.DATE(), nullable=True))
    op.create_foreign_key(u'transaction_ibfk_4', 'transaction', 'configtransactionstatus', ['status_id'], ['id'])
    op.add_column('product', sa.Column('amount_currency_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'product_ibfk_1', 'product', 'configcurrency', ['amount_currency_id'], ['id'])
    ### end Alembic commands ###
