"""empty message

Revision ID: 109070b76bcc
Revises: 5265cd480689
Create Date: 2016-09-25 17:14:07.429870

"""

# revision identifiers, used by Alembic.
revision = '109070b76bcc'
down_revision = '5265cd480689'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paypaltransaction', 'update_time')
    op.drop_column('paypaltransaction', 'create_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('create_time', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('paypaltransaction', sa.Column('update_time', mysql.VARCHAR(length=30), nullable=True))
    ### end Alembic commands ###
