"""empty message

Revision ID: 11c7de72784f
Revises: 09db4afac225
Create Date: 2016-09-17 12:05:04.515459

"""

# revision identifiers, used by Alembic.
revision = '11c7de72784f'
down_revision = '09db4afac225'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('amount_currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'configcurrency', ['amount_currency_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'amount_currency_id')
    ### end Alembic commands ###
