"""empty message

Revision ID: 182db0573a31
Revises: ee0accdce3d5
Create Date: 2016-09-25 17:11:58.633923

"""

# revision identifiers, used by Alembic.
revision = '182db0573a31'
down_revision = 'ee0accdce3d5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paypaltransaction', 'update_time')
    op.drop_column('paypaltransaction', 'create_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('create_time', mysql.DATETIME(), nullable=False))
    op.add_column('paypaltransaction', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
