"""empty message

Revision ID: 196e2c2c9a18
Revises: af7a61e11c97
Create Date: 2016-09-22 14:03:30.168342

"""

# revision identifiers, used by Alembic.
revision = '196e2c2c9a18'
down_revision = 'af7a61e11c97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mobile_phone_no', table_name='mpesaprofile')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('mobile_phone_no', 'mpesaprofile', ['mobile_phone_no'], unique=True)
    ### end Alembic commands ###
