"""empty message

Revision ID: 1a9ab015f7c3
Revises: 53c91a5a28b6
Create Date: 2016-10-17 18:44:27.790414

"""

# revision identifiers, used by Alembic.
revision = '1a9ab015f7c3'
down_revision = '53c91a5a28b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_type', sa.Integer(), nullable=True),
    sa.Column('notification_type_id', sa.Integer(), nullable=False),
    sa.Column('message_subject', sa.String(length=255), nullable=True),
    sa.Column('message_recipient_id', sa.Integer(), nullable=False),
    sa.Column('message_sender', sa.String(length=100), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('date_delivered', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['notification_type_id'], ['confignotificationtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailmessage')
    ### end Alembic commands ###
