"""empty message

Revision ID: 1bf29a10db1f
Revises: 4d00a6fdca78
Create Date: 2016-09-15 13:11:54.610446

"""

# revision identifiers, used by Alembic.
revision = '1bf29a10db1f'
down_revision = '4d00a6fdca78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
