"""empty message

Revision ID: 22c6dbc2a679
Revises: 294c806c30ac
Create Date: 2016-09-15 11:52:45.166885

"""

# revision identifiers, used by Alembic.
revision = '22c6dbc2a679'
down_revision = '294c806c30ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configpaypalapiaccount', sa.Column('live', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configpaypalapiaccount', 'live')
    ### end Alembic commands ###
