"""empty message

Revision ID: 2412d76ed058
Revises: a10cc2773226
Create Date: 2016-09-22 10:56:13.546022

"""

# revision identifiers, used by Alembic.
revision = '2412d76ed058'
down_revision = 'a10cc2773226'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
