"""empty message

Revision ID: 32139d33be94
Revises: 418ba2571694
Create Date: 2016-09-15 19:04:12.614789

"""

# revision identifiers, used by Alembic.
revision = '32139d33be94'
down_revision = '418ba2571694'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
