"""empty message

Revision ID: 334b866cf2c0
Revises: 5171c9b6ae2d
Create Date: 2016-09-22 16:39:04.988889

"""

# revision identifiers, used by Alembic.
revision = '334b866cf2c0'
down_revision = '5171c9b6ae2d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paypaltoken')
    op.drop_index('payer_id', table_name='paypalprofile')
    op.drop_column('paypalprofile', 'payer_id')
    op.add_column('paypaltransaction', sa.Column('payer_id', sa.Integer(), nullable=True))
    op.add_column('paypaltransaction', sa.Column('paypal_payer_id', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'paypaltransaction', 'paypalprofile', ['payer_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paypaltransaction', type_='foreignkey')
    op.drop_column('paypaltransaction', 'paypal_payer_id')
    op.drop_column('paypaltransaction', 'payer_id')
    op.add_column('paypalprofile', sa.Column('payer_id', mysql.VARCHAR(length=20), nullable=True))
    op.create_index('payer_id', 'paypalprofile', ['payer_id'], unique=True)
    op.create_table('paypaltoken',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('scope', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('access_token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('refresh_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('token_type', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('expires_in', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('exires_at', sa.DATE(), nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=False),
    sa.Column('payer_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paypal_user_id', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], [u'paypalprofile.payer_id'], name=u'paypaltoken_ibfk_1'),
    sa.ForeignKeyConstraint(['paypal_user_id'], [u'paypalprofile.paypal_user_id'], name=u'paypaltoken_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
