"""empty message

Revision ID: 3effac6e1b49
Revises: 42118dcd63ff
Create Date: 2016-09-15 15:31:57.944832

"""

# revision identifiers, used by Alembic.
revision = '3effac6e1b49'
down_revision = '42118dcd63ff'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configpaypalaccountwebhook', sa.Column('paypal_api_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'configpaypalaccountwebhook', 'configpaypalapiaccount', ['paypal_api_id'], ['id'])
    op.drop_constraint(u'configwebhookeventtype_ibfk_1', 'configwebhookeventtype', type_='foreignkey')
    op.drop_column('configwebhookeventtype', 'paypal_api_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configwebhookeventtype', sa.Column('paypal_api_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'configwebhookeventtype_ibfk_1', 'configwebhookeventtype', 'configpaypalapiaccount', ['paypal_api_id'], ['id'])
    op.drop_constraint(None, 'configpaypalaccountwebhook', type_='foreignkey')
    op.drop_column('configpaypalaccountwebhook', 'paypal_api_id')
    ### end Alembic commands ###
