"""empty message

Revision ID: 414fa650471b
Revises: 22c6dbc2a679
Create Date: 2016-09-15 12:22:13.836413

"""

# revision identifiers, used by Alembic.
revision = '414fa650471b'
down_revision = '22c6dbc2a679'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configpaypalaccountwebhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configwebhookeventtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('paypal_api_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['paypal_api_id'], ['configpaypalapiaccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'configpaypalapiaccount', sa.Column('account_email', sa.String(length=100), nullable=True))
    op.add_column(u'configpaypalapiaccount', sa.Column('client_id', sa.String(length=100), nullable=True))
    op.add_column(u'configpaypalapiaccount', sa.Column('client_secret', sa.String(length=100), nullable=True))
    op.drop_column(u'configpaypalapiaccount', 'private_key')
    op.drop_column(u'configpaypalapiaccount', 'credit_card_enabled')
    op.drop_column(u'configpaypalapiaccount', 'access_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'configpaypalapiaccount', sa.Column('access_id', mysql.VARCHAR(length=100), nullable=True))
    op.add_column(u'configpaypalapiaccount', sa.Column('credit_card_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'configpaypalapiaccount', sa.Column('private_key', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column(u'configpaypalapiaccount', 'client_secret')
    op.drop_column(u'configpaypalapiaccount', 'client_id')
    op.drop_column(u'configpaypalapiaccount', 'account_email')
    op.drop_table('configwebhookeventtype')
    op.drop_table('configpaypalaccountwebhook')
    ### end Alembic commands ###
