"""empty message

Revision ID: 418ba2571694
Revises: 3effac6e1b49
Create Date: 2016-09-15 18:41:46.671436

"""

# revision identifiers, used by Alembic.
revision = '418ba2571694'
down_revision = '3effac6e1b49'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confignotificationtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('confignotificationtemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('notification_type_id', sa.Integer(), nullable=True),
    sa.Column('email_template', sa.String(length=500), nullable=True),
    sa.Column('sms_template', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['notification_type_id'], ['confignotificationtype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('emailmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_type', sa.Integer(), nullable=True),
    sa.Column('email_arguments', sa.String(length=255), nullable=True),
    sa.Column('message_recipient', sa.String(length=100), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_delivered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['confignotificationtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('configsmstemplate')
    op.add_column(u'smsmessage', sa.Column('date_delivered', sa.DateTime(), nullable=True))
    op.add_column(u'smsmessage', sa.Column('message_arguments', sa.String(length=255), nullable=True))
    op.add_column(u'smsmessage', sa.Column('template_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'smsmessage_ibfk_2', 'smsmessage', type_='foreignkey')
    op.create_foreign_key(None, 'smsmessage', 'confignotificationtemplate', ['template_id'], ['id'])
    op.drop_column(u'smsmessage', 'message_text')
    op.drop_column(u'smsmessage', 'sms_template_id')
    op.add_column(u'user', sa.Column('date_joined', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('last_login', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'last_login')
    op.drop_column(u'user', 'date_joined')
    op.add_column(u'smsmessage', sa.Column('sms_template_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'smsmessage', sa.Column('message_text', mysql.VARCHAR(length=160), nullable=True))
    op.drop_constraint(None, 'smsmessage', type_='foreignkey')
    op.create_foreign_key(u'smsmessage_ibfk_2', 'smsmessage', 'configsmstemplate', ['sms_template_id'], ['id'])
    op.drop_column(u'smsmessage', 'template_id')
    op.drop_column(u'smsmessage', 'message_arguments')
    op.drop_column(u'smsmessage', 'date_delivered')
    op.create_table('configsmstemplate',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('template', mysql.VARCHAR(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('emailmessage')
    op.drop_table('confignotificationtemplate')
    op.drop_table('confignotificationtype')
    ### end Alembic commands ###
