"""empty message

Revision ID: 42118dcd63ff
Revises: e31cd07f367
Create Date: 2016-09-15 14:21:01.090022

"""

# revision identifiers, used by Alembic.
revision = '42118dcd63ff'
down_revision = 'e31cd07f367'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
