"""empty message

Revision ID: 42b597636881
Revises: 928ff2746845
Create Date: 2016-10-17 14:31:30.575389

"""

# revision identifiers, used by Alembic.
revision = '42b597636881'
down_revision = '928ff2746845'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'smsmessage_ibfk_1', 'smsmessage', type_='foreignkey')
    op.drop_column('smsmessage', 'sms_gateway_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smsmessage', sa.Column('sms_gateway_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'smsmessage_ibfk_1', 'smsmessage', 'configsmsgateway', ['sms_gateway_id'], ['id'])
    ### end Alembic commands ###
