"""empty message

Revision ID: 454d9578c0be
Revises: 4aff57316e6b
Create Date: 2016-09-22 14:41:49.232461

"""

# revision identifiers, used by Alembic.
revision = '454d9578c0be'
down_revision = '4aff57316e6b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configpaypalparameter', 'date_created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configpaypalparameter', 'date_created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    ### end Alembic commands ###
