"""empty message

Revision ID: 4729bbfd4960
Revises: 534d70ab0902
Create Date: 2016-10-07 15:02:44.370283

"""

# revision identifiers, used by Alembic.
revision = '4729bbfd4960'
down_revision = '534d70ab0902'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('mpesa_recipient', sa.String(length=25), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paypaltransaction', 'mpesa_recipient')
    ### end Alembic commands ###
