"""empty message

Revision ID: 48dcb327759b
Revises: 51a0be11c3ce
Create Date: 2016-09-22 16:04:05.092639

"""

# revision identifiers, used by Alembic.
revision = '48dcb327759b'
down_revision = '51a0be11c3ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypalprofile', sa.Column('birthday', sa.Date(), nullable=False))
    op.drop_column('paypalprofile', 'date_of_birth')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypalprofile', sa.Column('date_of_birth', sa.DATE(), nullable=False))
    op.drop_column('paypalprofile', 'birthday')
    ### end Alembic commands ###
