"""empty message

Revision ID: 4aff57316e6b
Revises: be2e1a9efd6e
Create Date: 2016-09-22 14:40:34.838402

"""

# revision identifiers, used by Alembic.
revision = '4aff57316e6b'
down_revision = 'be2e1a9efd6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypalprofile', sa.Column('middle_name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paypalprofile', 'middle_name')
    ### end Alembic commands ###
