"""empty message

Revision ID: 4b8e417d1564
Revises: b2e11c97f93a
Create Date: 2016-09-20 18:13:49.210878

"""

# revision identifiers, used by Alembic.
revision = '4b8e417d1564'
down_revision = 'b2e11c97f93a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configpaypalparameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paypal_charge_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paypal_charge_constant', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('foreign_exchange_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('foreign_charge_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('foreign_charge_constant', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('service_charge_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('service_charge_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mobile_money_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configpaypalparameter')
    ### end Alembic commands ###
