"""empty message

Revision ID: 4d00a6fdca78
Revises: 4f7d23035109
Create Date: 2016-09-15 13:01:09.937944

"""

# revision identifiers, used by Alembic.
revision = '4d00a6fdca78'
down_revision = '4f7d23035109'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
