"""empty message

Revision ID: 4f7d23035109
Revises: 414fa650471b
Create Date: 2016-09-15 12:38:34.808412

"""

# revision identifiers, used by Alembic.
revision = '4f7d23035109'
down_revision = '414fa650471b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configpaypalaccountwebhook', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('configpaypalaccountwebhook', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('configpaypalaccountwebhook', sa.Column('url_for', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configpaypalaccountwebhook', 'url_for')
    op.drop_column('configpaypalaccountwebhook', 'name')
    op.drop_column('configpaypalaccountwebhook', 'code')
    ### end Alembic commands ###
