"""empty message

Revision ID: 51183b1fab77
Revises: 8db438e2ea26
Create Date: 2016-09-17 12:13:53.580466

"""

# revision identifiers, used by Alembic.
revision = '51183b1fab77'
down_revision = '8db438e2ea26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
