"""empty message

Revision ID: 5171c9b6ae2d
Revises: aa45cc6f0b1b
Create Date: 2016-09-22 16:32:32.553746

"""

# revision identifiers, used by Alembic.
revision = '5171c9b6ae2d'
down_revision = 'aa45cc6f0b1b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'paypaltransaction_ibfk_3', 'paypaltransaction', type_='foreignkey')
    op.drop_column('paypaltransaction', 'paypal_payer_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('paypal_payer_id', mysql.VARCHAR(length=50), nullable=True))
    op.create_foreign_key(u'paypaltransaction_ibfk_3', 'paypaltransaction', 'paypalprofile', ['paypal_payer_id'], ['payer_id'])
    ### end Alembic commands ###
