"""empty message

Revision ID: 52095afd02d6
Revises: b5c702afe5a9
Create Date: 2016-10-17 06:23:58.681608

"""

# revision identifiers, used by Alembic.
revision = '52095afd02d6'
down_revision = 'b5c702afe5a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configpaypalparameter', sa.Column('foreign_currency', sa.String(length=3), nullable=True))
    op.add_column('configpaypalparameter', sa.Column('local_currency', sa.String(length=3), nullable=True))
    op.add_column('configpaypalparameter', sa.Column('service_charge_constant', sa.Numeric(precision=5, scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configpaypalparameter', 'service_charge_constant')
    op.drop_column('configpaypalparameter', 'local_currency')
    op.drop_column('configpaypalparameter', 'foreign_currency')
    ### end Alembic commands ###
