"""empty message

Revision ID: 534d70ab0902
Revises: 44e435320765
Create Date: 2016-10-07 06:48:00.922364

"""

# revision identifiers, used by Alembic.
revision = '534d70ab0902'
down_revision = '44e435320765'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configpaypalaccountwebhook')
    op.drop_table('configpaypalapiaccount')
    op.drop_table('configwebhookeventtype')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configwebhookeventtype',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('configpaypalapiaccount',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=True),
    sa.Column('live', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('account_email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('client_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('client_secret', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('configpaypalaccountwebhook',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('url_for', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('paypal_api_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paypal_api_id'], [u'configpaypalapiaccount.id'], name=u'configpaypalaccountwebhook_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
