"""empty message

Revision ID: 53c91a5a28b6
Revises: a9d2246b2a01
Create Date: 2016-10-17 18:43:39.963106

"""

# revision identifiers, used by Alembic.
revision = '53c91a5a28b6'
down_revision = 'a9d2246b2a01'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailmessage')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailmessage',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message_recipient', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('message_sender', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('delivered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_delivered', mysql.DATETIME(), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('message_subject', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('notification_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], [u'confignotificationtype.id'], name=u'emailmessage_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
