"""empty message

Revision ID: 558724ab90d4
Revises: d9a6c1b78771
Create Date: 2016-09-17 20:09:02.167489

"""

# revision identifiers, used by Alembic.
revision = '558724ab90d4'
down_revision = 'd9a6c1b78771'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactionstatus', 'transaction_status_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactionstatus', sa.Column('transaction_status_date', sa.DATE(), nullable=True))
    ### end Alembic commands ###
