"""empty message

Revision ID: 562eae7d587e
Revises: 32139d33be94
Create Date: 2016-09-15 19:32:35.729608

"""

# revision identifiers, used by Alembic.
revision = '562eae7d587e'
down_revision = '32139d33be94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
