"""empty message

Revision ID: 5f9778692714
Revises: 11c7de72784f
Create Date: 2016-09-17 12:07:52.630103

"""

# revision identifiers, used by Alembic.
revision = '5f9778692714'
down_revision = '11c7de72784f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
