"""empty message

Revision ID: 6334b767fbed
Revises: 82024a827828
Create Date: 2016-09-25 09:51:00.573353

"""

# revision identifiers, used by Alembic.
revision = '6334b767fbed'
down_revision = '82024a827828'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpesaprofile', 'registered_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpesaprofile', 'registered_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    ### end Alembic commands ###
