"""empty message

Revision ID: 646ba761e304
Revises: 99d7ec2fc478
Create Date: 2016-09-21 18:12:13.259769

"""

# revision identifiers, used by Alembic.
revision = '646ba761e304'
down_revision = '99d7ec2fc478'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='configpaypaltransactiontype')
    op.create_unique_constraint(None, 'configpaypaltransactiontype', ['code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'configpaypaltransactiontype', type_='unique')
    op.create_index('name', 'configpaypaltransactiontype', ['name'], unique=True)
    ### end Alembic commands ###
