"""empty message

Revision ID: 69875ca3d2dc
Revises: b2bec2b17c47
Create Date: 2016-09-22 06:48:25.049981

"""

# revision identifiers, used by Alembic.
revision = '69875ca3d2dc'
down_revision = 'b2bec2b17c47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
