"""empty message

Revision ID: 7a73f487bdca
Revises: 52095afd02d6
Create Date: 2016-10-17 06:47:02.307350

"""

# revision identifiers, used by Alembic.
revision = '7a73f487bdca'
down_revision = '52095afd02d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configpaypalparameter', sa.Column('foreign_charge_constant_currency', sa.String(length=3), nullable=True))
    op.add_column('configpaypalparameter', sa.Column('mobile_money_charge_currency', sa.String(length=3), nullable=True))
    op.add_column('configpaypalparameter', sa.Column('paypal_charge_constant_currency', sa.String(length=3), nullable=True))
    op.add_column('configpaypalparameter', sa.Column('service_charge_constant_currency', sa.String(length=3), nullable=True))
    op.add_column('configpaypalparameter', sa.Column('service_charge_max_currency', sa.String(length=3), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configpaypalparameter', 'service_charge_max_currency')
    op.drop_column('configpaypalparameter', 'service_charge_constant_currency')
    op.drop_column('configpaypalparameter', 'paypal_charge_constant_currency')
    op.drop_column('configpaypalparameter', 'mobile_money_charge_currency')
    op.drop_column('configpaypalparameter', 'foreign_charge_constant_currency')
    ### end Alembic commands ###
