"""empty message

Revision ID: 7e8b2b13f58a
Revises: 2412d76ed058
Create Date: 2016-09-22 10:56:40.604687

"""

# revision identifiers, used by Alembic.
revision = '7e8b2b13f58a'
down_revision = '2412d76ed058'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
