"""empty message

Revision ID: 82024a827828
Revises: bac65eb16d07
Create Date: 2016-09-25 09:45:32.747474

"""

# revision identifiers, used by Alembic.
revision = '82024a827828'
down_revision = 'bac65eb16d07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesaprofile', sa.Column('registered_name', sa.String(length=100), nullable=False))
    op.drop_constraint(u'mpesaprofile_ibfk_1', 'mpesaprofile', type_='foreignkey')
    op.drop_column('mpesaprofile', 'account_id')
    op.drop_constraint(u'paypalprofile_ibfk_1', 'paypalprofile', type_='foreignkey')
    op.drop_column('paypalprofile', 'account_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypalprofile', sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'paypalprofile_ibfk_1', 'paypalprofile', 'account', ['account_id'], ['id'])
    op.add_column('mpesaprofile', sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'mpesaprofile_ibfk_1', 'mpesaprofile', 'account', ['account_id'], ['id'])
    op.drop_column('mpesaprofile', 'registered_name')
    ### end Alembic commands ###
