"""empty message

Revision ID: 8db438e2ea26
Revises: c1f79613521d
Create Date: 2016-09-17 12:12:44.796186

"""

# revision identifiers, used by Alembic.
revision = '8db438e2ea26'
down_revision = 'c1f79613521d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('amount_currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'configcurrency', ['amount_currency_id'], ['id'])
    op.drop_column('account', 'account_status_date')
    op.drop_column('account', 'last_withdraw_date')
    op.drop_column('account', 'last_deposit_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('last_deposit_date', sa.DATE(), nullable=True))
    op.add_column('account', sa.Column('last_withdraw_date', sa.DATE(), nullable=True))
    op.add_column('account', sa.Column('account_status_date', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'amount_currency_id')
    ### end Alembic commands ###
