"""empty message

Revision ID: 937277769ddf
Revises: e35aeb061ad6
Create Date: 2016-09-21 17:59:20.838575

"""

# revision identifiers, used by Alembic.
revision = '937277769ddf'
down_revision = 'e35aeb061ad6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltoken', sa.Column('payer_id', sa.String(length=50), nullable=True))
    op.add_column('paypaltoken', sa.Column('paypal_user_id', sa.String(length=50), nullable=True))
    op.alter_column('paypaltoken', 'access_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('paypaltoken', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('paypaltoken', 'exires_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('paypaltoken', 'expires_in',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('paypaltoken', 'token_type',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.create_foreign_key(None, 'paypaltoken', 'paypalprofile', ['payer_id'], ['payer_id'])
    op.create_foreign_key(None, 'paypaltoken', 'paypalprofile', ['paypal_user_id'], ['paypal_user_id'])
    op.alter_column('paypaltransaction', 'create_time',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('paypaltransaction', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('paypaltransaction', 'state',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('paypaltransaction', 'update_time',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('paypaltransaction', 'paypal_transaction_type_code')
    op.drop_column('paypaltransaction', 'transaction_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('transaction_id', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('paypaltransaction', sa.Column('paypal_transaction_type_code', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('paypaltransaction', 'update_time',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('paypaltransaction', 'state',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('paypaltransaction', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('paypaltransaction', 'create_time',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'paypaltoken', type_='foreignkey')
    op.drop_constraint(None, 'paypaltoken', type_='foreignkey')
    op.alter_column('paypaltoken', 'token_type',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('paypaltoken', 'expires_in',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('paypaltoken', 'exires_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('paypaltoken', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('paypaltoken', 'access_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('paypaltoken', 'paypal_user_id')
    op.drop_column('paypaltoken', 'payer_id')
    ### end Alembic commands ###
