"""empty message

Revision ID: 93e27f53e870
Revises: cc2f8b25f5db
Create Date: 2016-09-17 20:29:27.199853

"""

# revision identifiers, used by Alembic.
revision = '93e27f53e870'
down_revision = 'cc2f8b25f5db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configledgeraccount', sa.Column('balance_direction', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configledgeraccount', 'balance_direction')
    ### end Alembic commands ###
