"""empty message

Revision ID: 99d7ec2fc478
Revises: 937277769ddf
Create Date: 2016-09-21 18:00:16.637323

"""

# revision identifiers, used by Alembic.
revision = '99d7ec2fc478'
down_revision = '937277769ddf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
