"""empty message

Revision ID: 9effdc1d4cc6
Revises: 4b8e417d1564
Create Date: 2016-09-21 15:08:01.667018

"""

# revision identifiers, used by Alembic.
revision = '9effdc1d4cc6'
down_revision = '4b8e417d1564'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'paypaltransaction_ibfk_2', 'paypaltransaction', type_='foreignkey')
    op.drop_column('paypaltransaction', 'parent_transaction_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('parent_transaction_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'paypaltransaction_ibfk_2', 'paypaltransaction', 'transaction', ['parent_transaction_id'], ['id'])
    ### end Alembic commands ###
