"""empty message

Revision ID: a10cc2773226
Revises: 69875ca3d2dc
Create Date: 2016-09-22 10:49:29.777509

"""

# revision identifiers, used by Alembic.
revision = 'a10cc2773226'
down_revision = '69875ca3d2dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paypalprofile', 'account_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('paypalprofile', 'account_type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('paypalprofile', 'age_range',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('paypalprofile', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('paypalprofile', 'date_updated',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('paypalprofile', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paypalprofile', 'email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('paypalprofile', 'family_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paypalprofile', 'gender',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('paypalprofile', 'given_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paypalprofile', 'middle_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paypalprofile', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paypalprofile', 'payer_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('paypalprofile', 'paypal_user_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('paypalprofile', 'phone_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('paypalprofile', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('paypalprofile', 'verified_account',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    op.alter_column('paypalprofile', 'verified_account',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('paypalprofile', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('paypalprofile', 'phone_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paypalprofile', 'paypal_user_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('paypalprofile', 'payer_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('paypalprofile', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paypalprofile', 'middle_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paypalprofile', 'given_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paypalprofile', 'gender',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('paypalprofile', 'family_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paypalprofile', 'email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('paypalprofile', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('paypalprofile', 'date_updated',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('paypalprofile', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('paypalprofile', 'age_range',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('paypalprofile', 'account_type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('paypalprofile', 'account_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
