"""empty message

Revision ID: a950f42e86f8
Revises: d385188dff50
Create Date: 2016-10-17 18:42:18.799548

"""

# revision identifiers, used by Alembic.
revision = 'a950f42e86f8'
down_revision = 'd385188dff50'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smsmessage')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smsmessage',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('message_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message_sender', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('delivered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_delivered', mysql.DATETIME(), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=320), nullable=True),
    sa.Column('notification_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message_recepient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], [u'confignotificationtype.id'], name=u'smsmessage_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
