"""empty message

Revision ID: a9d2246b2a01
Revises: a950f42e86f8
Create Date: 2016-10-17 18:42:45.711517

"""

# revision identifiers, used by Alembic.
revision = 'a9d2246b2a01'
down_revision = 'a950f42e86f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smsmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_type_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Integer(), nullable=True),
    sa.Column('message_sender', sa.String(length=15), nullable=True),
    sa.Column('message', sa.String(length=320), nullable=True),
    sa.Column('message_recepient_id', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('date_delivered', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_recepient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['notification_type_id'], ['confignotificationtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smsmessage')
    ### end Alembic commands ###
