"""empty message

Revision ID: aa45cc6f0b1b
Revises: 48dcb327759b
Create Date: 2016-09-22 16:24:10.320308

"""

# revision identifiers, used by Alembic.
revision = 'aa45cc6f0b1b'
down_revision = '48dcb327759b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
