"""empty message

Revision ID: af7a61e11c97
Revises: aaa49e535183
Create Date: 2016-09-22 13:59:20.923369

"""

# revision identifiers, used by Alembic.
revision = 'af7a61e11c97'
down_revision = 'aaa49e535183'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'paypalprofile_ibfk_2', 'paypalprofile', type_='foreignkey')
    op.drop_column('paypalprofile', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypalprofile', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'paypalprofile_ibfk_2', 'paypalprofile', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
