"""empty message

Revision ID: b2bec2b17c47
Revises: ee560c3a61f0
Create Date: 2016-09-21 18:42:48.667681

"""

# revision identifiers, used by Alembic.
revision = 'b2bec2b17c47'
down_revision = 'ee560c3a61f0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paypaltransaction', 'paypal_transaction_type_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paypaltransaction', 'paypal_transaction_type_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###
