"""empty message

Revision ID: b5296491f9e6
Revises: d070178ec650
Create Date: 2016-09-21 18:20:55.145286

"""

# revision identifiers, used by Alembic.
revision = 'b5296491f9e6'
down_revision = 'd070178ec650'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configpaypaltransactiontype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column(u'paypaltransaction', sa.Column('paypal_transaction_type_code', sa.String(length=50), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'paypaltransaction', 'paypal_transaction_type_code')
    op.drop_table('configpaypaltransactiontype')
    ### end Alembic commands ###
