"""empty message

Revision ID: b5c702afe5a9
Revises: 4729bbfd4960
Create Date: 2016-10-12 08:27:32.889560

"""

# revision identifiers, used by Alembic.
revision = 'b5c702afe5a9'
down_revision = '4729bbfd4960'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.drop_column('user', 'active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'phone_verified')
    op.drop_column('user', 'email_verified')
    ### end Alembic commands ###
