"""empty message

Revision ID: be2e1a9efd6e
Revises: d583524f09bb
Create Date: 2016-09-22 14:32:28.931115

"""

# revision identifiers, used by Alembic.
revision = 'be2e1a9efd6e'
down_revision = 'd583524f09bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
