"""empty message

Revision ID: c1f79613521d
Revises: 5f9778692714
Create Date: 2016-09-17 12:08:15.181872

"""

# revision identifiers, used by Alembic.
revision = 'c1f79613521d'
down_revision = '5f9778692714'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
