"""empty message

Revision ID: c2733aba1a2a
Revises: 425863977cfb
Create Date: 2016-09-22 13:51:38.684614

"""

# revision identifiers, used by Alembic.
revision = 'c2733aba1a2a'
down_revision = '425863977cfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
