"""empty message

Revision ID: c4971d810083
Revises: 196e2c2c9a18
Create Date: 2016-09-22 14:07:38.372025

"""

# revision identifiers, used by Alembic.
revision = 'c4971d810083'
down_revision = '196e2c2c9a18'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('date_updated', sa.DateTime(), nullable=False))
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'date_joined',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'last_login',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'last_login',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'date_joined',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('user', 'date_updated')
    op.drop_column('user', 'date_created')
    ### end Alembic commands ###
