"""empty message

Revision ID: c86e9c8a1d0a
Revises: e3f23afe2f21
Create Date: 2016-09-25 16:38:51.249512

"""

# revision identifiers, used by Alembic.
revision = 'c86e9c8a1d0a'
down_revision = 'e3f23afe2f21'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paypaltransaction', 'update_time')
    op.drop_column('paypaltransaction', 'create_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('create_time', mysql.DATETIME(), nullable=False))
    op.add_column('paypaltransaction', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
