"""empty message

Revision ID: cc2f8b25f5db
Revises: 558724ab90d4
Create Date: 2016-09-17 20:28:22.218473

"""

# revision identifiers, used by Alembic.
revision = 'cc2f8b25f5db'
down_revision = '558724ab90d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configledgeraccount', 'balance_direction')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configledgeraccount', sa.Column('balance_direction', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
