"""empty message

Revision ID: cde981c615f0
Revises: None
Create Date: 2016-10-07 06:27:13.772012

"""

# revision identifiers, used by Alembic.
revision = 'cde981c615f0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpesatransaction')
    op.add_column('smsmessage', sa.Column('message', sa.String(length=320), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smsmessage', 'message')
    ### end Alembic commands ###
