"""empty message

Revision ID: d070178ec650
Revises: 646ba761e304
Create Date: 2016-09-21 18:20:38.621958

"""

# revision identifiers, used by Alembic.
revision = 'd070178ec650'
down_revision = '646ba761e304'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configpaypaltransactiontype')
    op.drop_column('paypaltransaction', 'paypal_transaction_type_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('paypal_transaction_type_code', mysql.VARCHAR(length=50), nullable=True))
    op.create_table('configpaypaltransactiontype',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
