"""empty message

Revision ID: d43dda785144
Revises: c2733aba1a2a
Create Date: 2016-09-22 13:52:34.532742

"""

# revision identifiers, used by Alembic.
revision = 'd43dda785144'
down_revision = 'c2733aba1a2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['phone'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    ### end Alembic commands ###
