"""empty message

Revision ID: d566942b5bac
Revises: e426ef99dc97
Create Date: 2016-09-21 17:02:15.286085

"""

# revision identifiers, used by Alembic.
revision = 'd566942b5bac'
down_revision = 'e426ef99dc97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('transaction_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'paypaltransaction', 'transaction', ['transaction_id'], ['transaction_no'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paypaltransaction', type_='foreignkey')
    op.drop_column('paypaltransaction', 'transaction_id')
    ### end Alembic commands ###
