"""empty message

Revision ID: d583524f09bb
Revises: c4971d810083
Create Date: 2016-09-22 14:08:34.172825

"""

# revision identifiers, used by Alembic.
revision = 'd583524f09bb'
down_revision = 'c4971d810083'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login',
               existing_type=mysql.DATETIME(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login',
               existing_type=mysql.DATETIME(),
               nullable=False)
    ### end Alembic commands ###
