"""empty message

Revision ID: d9a6c1b78771
Revises: fedddbf0e1bd
Create Date: 2016-09-17 20:02:21.428058

"""

# revision identifiers, used by Alembic.
revision = 'd9a6c1b78771'
down_revision = 'fedddbf0e1bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
