"""empty message

Revision ID: e31cd07f367
Revises: 1bf29a10db1f
Create Date: 2016-09-15 14:13:14.578541

"""

# revision identifiers, used by Alembic.
revision = 'e31cd07f367'
down_revision = '1bf29a10db1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configsmsgateway', sa.Column('api_key', sa.String(length=100), nullable=True))
    op.add_column('configsmsgateway', sa.Column('api_secret', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configsmsgateway', 'api_secret')
    op.drop_column('configsmsgateway', 'api_key')
    ### end Alembic commands ###
