"""empty message

Revision ID: e35aeb061ad6
Revises: d566942b5bac
Create Date: 2016-09-21 17:28:54.702732

"""

# revision identifiers, used by Alembic.
revision = 'e35aeb061ad6'
down_revision = 'd566942b5bac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configpaypaltransactiontype',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('code', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.add_column(u'paypaltransaction', sa.Column('paypal_transaction_id', sa.String(length=50), nullable=True))
    op.add_column(u'paypaltransaction', sa.Column('paypal_transaction_type_code', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'paypaltransaction', ['paypal_transaction_id'])
    op.drop_constraint(u'paypaltransaction_ibfk_5', 'paypaltransaction', type_='foreignkey')
    op.create_foreign_key(None, 'paypaltransaction', 'transaction', ['paypal_transaction_id'], ['transaction_no'])
    op.create_foreign_key(None, 'paypaltransaction', 'configpaypaltransactiontype', ['paypal_transaction_type_code'], ['code'])
    op.drop_column(u'paypaltransaction', 'transaction_id')
    ## end Alembic commands ###
    
def downgrade():
    ## commands auto generated by Alembic - please adjust! ###
    op.add_column(u'paypaltransaction', sa.Column('transaction_id', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'paypaltransaction', type_='foreignkey')
    op.drop_constraint(None, 'paypaltransaction', type_='foreignkey')
    op.create_foreign_key(u'paypaltransaction_ibfk_5', 'paypaltransaction', 'transaction', ['transaction_id'], ['transaction_no'])
    op.drop_constraint(None, 'paypaltransaction', type_='unique')
    op.drop_column(u'paypaltransaction', 'paypal_transaction_type_code')
    op.drop_column(u'paypaltransaction', 'paypal_transaction_id')
    op.drop_table('configpaypaltransactiontype')
    ## end Alembic commands ###
