"""empty message

Revision ID: e3f23afe2f21
Revises: 913c2fefea37
Create Date: 2016-09-25 15:16:43.982156

"""

# revision identifiers, used by Alembic.
revision = 'e3f23afe2f21'
down_revision = '913c2fefea37'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paypaltransaction', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paypaltransaction', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    ### end Alembic commands ###
