"""empty message

Revision ID: e6029f2bcc1d
Revises: 1a9ab015f7c3
Create Date: 2016-10-17 18:44:49.709025

"""

# revision identifiers, used by Alembic.
revision = 'e6029f2bcc1d'
down_revision = '1a9ab015f7c3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smsmessage', sa.Column('message_recipient_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'smsmessage_ibfk_1', 'smsmessage', type_='foreignkey')
    op.create_foreign_key(None, 'smsmessage', 'user', ['message_recipient_id'], ['id'])
    op.drop_column('smsmessage', 'message_recepient_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smsmessage', sa.Column('message_recepient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'smsmessage', type_='foreignkey')
    op.create_foreign_key(u'smsmessage_ibfk_1', 'smsmessage', 'user', ['message_recepient_id'], ['id'])
    op.drop_column('smsmessage', 'message_recipient_id')
    ### end Alembic commands ###
