"""empty message

Revision ID: e9f85b7234c7
Revises: c86e9c8a1d0a
Create Date: 2016-09-25 16:39:10.868806

"""

# revision identifiers, used by Alembic.
revision = 'e9f85b7234c7'
down_revision = 'c86e9c8a1d0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypaltransaction', sa.Column('create_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('paypaltransaction', sa.Column('update_time', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paypaltransaction', 'update_time')
    op.drop_column('paypaltransaction', 'create_time')
    ### end Alembic commands ###
