"""empty message

Revision ID: ed728aa00a42
Revises: 334b866cf2c0
Create Date: 2016-09-23 11:42:31.905229

"""

# revision identifiers, used by Alembic.
revision = 'ed728aa00a42'
down_revision = '334b866cf2c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
