"""empty message

Revision ID: ee0accdce3d5
Revises: e9f85b7234c7
Create Date: 2016-09-25 17:10:32.077302

"""

# revision identifiers, used by Alembic.
revision = 'ee0accdce3d5'
down_revision = 'e9f85b7234c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
