"""empty message

Revision ID: ee560c3a61f0
Revises: b5296491f9e6
Create Date: 2016-09-21 18:39:58.430107

"""

# revision identifiers, used by Alembic.
revision = 'ee560c3a61f0'
down_revision = 'b5296491f9e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
