"""empty message

Revision ID: fedddbf0e1bd
Revises: 51183b1fab77
Create Date: 2016-09-17 12:53:17.860413

"""

# revision identifiers, used by Alembic.
revision = 'fedddbf0e1bd'
down_revision = '51183b1fab77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configledgeraccountingrule', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'configledgeraccountingrule', 'product', ['product_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'configledgeraccountingrule', type_='foreignkey')
    op.drop_column('configledgeraccountingrule', 'product_id')
    ### end Alembic commands ###
