"""empty message

Revision ID: 3fbe4f2f89fa
Revises: None
Create Date: 2016-09-14 19:44:05.153472

"""

# revision identifiers, used by Alembic.
revision = '3fbe4f2f89fa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
